### ISSUE TITLE
provide install via Homebrew

### ISSUE THREAD

**Issue by zachvalenta** [red-data-tools/YouPlot#33]
Project looks great, just thinking it would be nice to have install available via os package manager as well.

**Comment by kojix2** [comment]
Actually, it never occurred to me to register YouPlot with homebrew until you suggested it. 
You are right. I should certainly do that.

I have [submitted the formula to add Youplot](https://github.com/Homebrew/homebrew-core/pull/120787). 
Once all the probrems are corrected, YouPlot will be able to be installed with homebrew.
Thank you very much.

**Comment by jpmc** [comment]
Just saw that they finally merged it in! [Formula Page](https://formulae.brew.sh/formula/youplot)

Just confirmed it installed effortlessly and works fine on my M1 Mac with that landmasses test on the README 👍

Thanks for the new addition to my toolbox!
