### ISSUE TITLE
Provide binary for linux

### ISSUE THREAD

**Issue by thenbe** [red-data-tools/YouPlot#34]
It'd be great to have a way to try out this package without going through the ruby toolchain.

This package looks interesting, but I couldn't find a way to try it out. I've never worked with ruby/gems before, and I ran into some file permission issues trying to set that all up. Having the package available through a cross-platform package manger would certainly be convenient, but a simple binary on github would be very useful at the moment; especially for us non-ruby folk.

Relevant:

- https://github.com/red-data-tools/YouPlot/issues/33
- https://github.com/red-data-tools/YouPlot/issues/32#issuecomment-1382720370

**Comment by kojix2** [comment]
I think Ruby is a scripting language like Python or Perl, so it is difficult to provide programs as binaries...

**Comment by mrkn** [comment]
Instead of providing a single binary for Linux, providing a small docker image can be a reasonable way to reduce installation difficulty.

**Comment by jpmc** [comment]
As per #33 being completed recently, you should now be able to use `brew install youplot` to get the binary and dependencies installed without needing Docker or installing gems yourself.

`brew` being a package manager for Mac and Linux: https://brew.sh/

https://formulae.brew.sh/formula/youplot

**Comment by thenbe** [comment]
We can close this ticket as youplot is now available on both homebrew and [nix](https://github.com/red-data-tools/YouPlot/issues/35).
