### ISSUE TITLE
Provide install via nix

### ISSUE THREAD

**Issue by gmagno** [red-data-tools/YouPlot#35]
Such a nice tool, thanks for the work you've put into this.

It would great to see `youplot` on https://github.com/NixOS/nixpkgs.

Related:

- #27 
- #32 
- #33 
- #34

**Comment by trueNAHO** [comment]
`youplot` is available since https://github.com/NixOS/nixpkgs/commit/dedef7343e3b5cacfc73d8dd85272a364ada639f.

**Comment by kojix2** [comment]
Thanks.
